config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root "homes#top"

  get "/home/about" => "homes#about"
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { minimum: 2, maximum: 20} , uniqueness: true
  validates :introduction, length: { maximum: 50 }

  has_many :books, dependent: :destroy
  attachment :profile_image

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about, :public_action]
  before_action :configure_permitted_parameters,if: :devise_controller?

    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
	  user_path(resource)
    end

  private
	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up, keys:[:email])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render 'index'  
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
        render "edit"
    else
        redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])    
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with model: book, local: true do |f| %>

  <div class="form-title row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "col-xs-12" %>
  </div>

  <div class="form-body row">
  	<%= f.label :Opinion %>
    <%= f.text_area :body, class: "col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit class: "btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <h1>Editing Book</h1>
      <%= render 'books/error', model: @book %>
      <%= render 'books/book', book: @book %>
    <div class="menu">
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
    </div>
  <div class="col-xs-3"></div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/error', model: @book%>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table book-index">
        <h2>Books</h2>
        <thead>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, fallback: "no_image.jpg"%></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<h1>Welcom to<i class="fas fa-book"></i>
  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
  <b>Bookers!!</b>
</h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
	<div class="col-md-6 col-md-offset-3">
	  <div class="top-text">
		<h1>welcom to<i class="fas fa-book"></i>
		  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
		  <b>Bookers!!</b>
		</h1>
		<p>In<i class="fas fa-book"></i>
		  <span class="glyphicon glyphicon-book" aria-hidden="true"></span>
		  <b>Bookers</b>,<br>
		  	you can share and exchange your opinions , inpresiions , and emotions<br>
		  	about various books!
		</p>
	  </div>
	<div class="row">
      <%= link_to "Log in", new_user_session_path, class:"btn btn-primary col-xs-10 col-xs-offset-1" %>
	</div>
	<div class="row">
	  <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-success col-xs-10 col-xs-offset-1" %>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="header">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-left">
               <%= link_to root_path do %>
               <span class="title">Bookers</span>
               <% end %>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="fas fa-user-cog">
                <%= link_to ' Home', user_path(current_user), class: 'fas fa-home nav-link text-light' %>
                
                <!--<span class="glyphicon glyphicon-home" aria-hidden="true"></span>-->
                <%# end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to users_path, class:"btn btn-link" do %>
                <span class="fas fa-users" aria-hidden="true">Users</span>
                <% end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to books_path, class:"btn btn-link" do %>
                <span class="fas fa-book-open" aria-hidden="true">Books</span>
                <% end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-link" do %>
                <span class="fas fa-sign-out-alt" aria-hidden="true">Logout</span>
                <% end %>
              </li>
            <% else %>
              <li class="fas fa-user-cog">
                <%= link_to root_path, class:"btn btn-link" do %>
                <span class="fas fa-home" aria-hidden="true">Home</span>
                <% end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to home_about_path, class:"btn btn-link" do %>
                <span class="fas fa-link" aria-hidden="true">About</span>
                <% end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to new_user_registration_path, class:"btn btn-link" do %>
                <span class="fas fa-user-plus" aria-hidden="true">sign up</span>
                <% end %>
              </li>
              <li class="fas fa-user-cog">
                <%= link_to new_user_session_path, class:"btn btn-link" do %>
                <span class="fas fa-sign-in-alt" aria-hidden="true">login</span>
                <% end %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>


        <footer>
          <p class="text-right"> CopyRight Infratop.inc</p>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<!--<div class="container">-->
  <!--<div class="row">-->
  <!--  <div class="col-md-8">-->
<table>
  <h2>User info</h2>
  <thead>
    <tr>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg"%>
    </tr>
  </thead>
  <tbody>
    <tr>
      <!--<div class="col-md-8">-->
      <td>Name</td>
      <td><%= user.name %></td>
    </tr>
    <tr>
      <!--<div class="col-md-8">-->
      <td>Introduction</td>
      <td><%= user.introduction %></td>
    </tr>
    </tbody>
  </table>
    <tr>
      <td colspan="2">
        <% if current_user.id == user.id %>
         <%= link_to edit_user_path(current_user), class:"btn btn-default btn-block" do %>
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
         <% end %>
        <% else %>
         <%= link_to edit_user_path(user.id), class:"btn btn-default btn-block" do  %>
          <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
         <% end %>
        <% end %>
      </td>
    </tr>

app/views/users/edit.html.erb
<h1>User info</h1>
<%= form_with model:(@user) do |f| %>
<%= render 'books/error', model: @user %>
  <div class="user-name">Name</div>
    <%= f.text_field :name %>
  <div class="user-edit-image">Image</div>
    <%= f.attachment_field :profile_image %>
  <div class="form-body">Introduction</div>
    <%= f.text_area :introduction %><br>
  <div class="upload">
    <%= f.submit " Update User" %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th></th>
  	    </thead>
  	    </div>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50,fallback: "no_image.jpg"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	  </div>
  	</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
      <table class="table table-user-show">
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%>
            <% end %></td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>